all: main.pdf

main.pdf: use_convex_hull.tex triangulationDelone.tex main.tex 
	pdflatex main.tex

#gamma.eps isect-1-a.eps isect-1-b.eps isect-2-a.eps isect-2-b.eps main.tex use_convex_hull.tex triangulation.tex
#gamma.eps: gamma.asy
#	asy gamma.asy

#isect-1-a.eps: isect-1-a.asy
#	asy isect-1-a.asy

#isect-1-b.eps: isect-1-b.asy
#	asy isect-1-b.asy

#isect-2-a.eps: isect-2-a.asy
#	asy isect-2-a.asy

#isect-2-b.eps: isect-2-b.asy
#	asy isect-2-b.asy
